Data extraction for creating a dashboard in tablue for carib

In [33]:
import requests
import pandas as pd
import io
import urllib.parse

In [34]:
WFS_URL = "https://openmaps.gov.bc.ca/geo/pub/wfs"

LAYER_HISTORICAL = "pub:WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL_FIRE_POLYS_SP"
LAYER_CURRENT = "pub:WHSE_LAND_AND_NATURAL_RESOURCE.PROT_CURRENT_FIRE_POLYS_SP"


REGION_NAME = "Cariboo Fire Centre"
START_YEAR = 2001
CURRENT_YEAR = 2024

In [35]:
def get_wfs_data(layer_name, cql_filter=None):
    """
    Fetches data from the BC WFS service and returns a Pandas DataFrame.
    """
    params = {
        "service": "WFS",
        "version": "2.0.0",
        "request": "GetFeature",
        "typeNames": layer_name,
        "outputFormat": "csv",
        "srsName": "EPSG:4326",  # Latitude/Longitude
    }
    
    if cql_filter:
        params["CQL_FILTER"] = cql_filter

    print(f"Requesting data from layer: {layer_name}...")
    try:
        response = requests.get(WFS_URL, params=params, timeout=60)
        response.raise_for_status()
        
        # Check if empty
        if not response.content:
            print("No data returned.")
            return pd.DataFrame()
            
        # Parse CSV content
        df = pd.read_csv(io.StringIO(response.text))
        return df
    except Exception as e:
        print(f"Error fetching data: {e}")
        return pd.DataFrame()

In [39]:
cql_hist = f"FIRE_YEAR >= {START_YEAR}"
df_hist = get_wfs_data(LAYER_HISTORICAL, cql_hist)

Requesting data from layer: pub:WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL_FIRE_POLYS_SP...

In [40]:
df_hist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7109 entries, 0 to 7108
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   FID                 7109 non-null   object
 1   FIRE_NUMBER         7109 non-null   object
 2   VERSION_NUMBER      6487 non-null   float64
 3   FIRE_YEAR           7109 non-null   int64
 4   FIRE_CAUSE          7109 non-null   object
 5   FIRE_LABEL          7109 non-null   object
 6   FIRE_SIZE_HECTARES  7108 non-null   float64
 7   SOURCE              7031 non-null   object
 8   GPS_TRACK_DATE      6668 non-null   object
 9   LOAD_DATE           7029 non-null   object
 10  FIRE_DATE           7105 non-null   object
 11  CREATION_METHOD     7107 non-null   object
 12  FEATURE_CODE        7109 non-null   object
 13  SHAPE               7109 non-null   object
 14  OBJECTID            7109 non-null   int64
 15  SE_ANNO_CAD_DATA    0 non-null      float64
 16  FEATURE_AREA_SQM    7109 non-null   float64
 17  FEATURE_LENGTH_M    7109 non-null   float64
dtypes: float64(5), int64(2), object(11)
memory usage: 999.8+ KB

In [41]:
df_hist.FIRE_YEAR

0       2023
1       2003
2       2003
3       2003
4       2003
        ...
7104    2024
7105    2024
7106    2024
7107    2024
7108    2024
Name: FIRE_YEAR, Length: 7109, dtype: int64

In [5]:
df_curr = get_wfs_data(LAYER_CURRENT)

Requesting data from layer: pub:WHSE_LAND_AND_NATURAL_RESOURCE.PROT_CURRENT_FIRE_POLYS_SP...

In [6]:
df_hist.head()

,FID,FIRE_NUMBER,VERSION_NUMBER,FIRE_YEAR,FIRE_CAUSE,FIRE_LABEL,FIRE_SIZE_HECTARES,SOURCE,GPS_TRACK_DATE,LOAD_DATE,FIRE_DATE,CREATION_METHOD,FEATURE_CODE,SHAPE,OBJECTID,SE_ANNO_CAD_DATA,FEATURE_AREA_SQM,FEATURE_LENGTH_M
0,WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL...,G73561,NaN,2023,Unknown,2023-G73561,5.0,Non-corrected ground GPS,NaN,NaN,NaN,NaN,JA70003000,POLYGON ((-121.66126999865841 55.4179900000132...,3157167,NaN,5.015902e+04,2035.1685
1,WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL...,K20298,NaN,2003,Person,2003-K20298,6228.1,LANDSAT5,NaN,2007-05-17,2003-08-01,digitized,JA70003000,POLYGON ((-120.21870546913227 50.7950459566509...,3174540,NaN,6.228192e+07,35243.8021
2,WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL...,K20436,NaN,2003,Lightning,2003-K20436,4313.0,LANDSAT5,NaN,2007-05-17,2003-08-07,digitized,JA70003000,POLYGON ((-119.76609292678498 51.3914763721292...,3174541,NaN,4.313028e+07,47591.3012
3,WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL...,K20624,NaN,2003,Person,2003-K20624,5220.6,LANDSAT5,NaN,2007-05-17,2003-08-15,digitized,JA70003000,POLYGON ((-121.37462997350404 50.7053453953040...,3174542,NaN,5.220610e+07,55395.5108
4,WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL...,K20627,NaN,2003,Lightning,2003-K20627,10878.8,LANDSAT5,NaN,2007-05-17,2003-08-15,digitized,JA70003000,POLYGON ((-119.74093407523235 50.8004608657691...,3174543,NaN,1.087881e+08,99764.7895

In [7]:
df_hist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7109 entries, 0 to 7108
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   FID                 7109 non-null   object
 1   FIRE_NUMBER         7109 non-null   object
 2   VERSION_NUMBER      6487 non-null   float64
 3   FIRE_YEAR           7109 non-null   int64
 4   FIRE_CAUSE          7109 non-null   object
 5   FIRE_LABEL          7109 non-null   object
 6   FIRE_SIZE_HECTARES  7108 non-null   float64
 7   SOURCE              7031 non-null   object
 8   GPS_TRACK_DATE      6668 non-null   object
 9   LOAD_DATE           7029 non-null   object
 10  FIRE_DATE           7105 non-null   object
 11  CREATION_METHOD     7107 non-null   object
 12  FEATURE_CODE        7109 non-null   object
 13  SHAPE               7109 non-null   object
 14  OBJECTID            7109 non-null   int64
 15  SE_ANNO_CAD_DATA    0 non-null      float64
 16  FEATURE_AREA_SQM    7109 non-null   float64
 17  FEATURE_LENGTH_M    7109 non-null   float64
dtypes: float64(5), int64(2), object(11)
memory usage: 999.8+ KB

In [28]:
df_curr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   FID                 320 non-null    object
 1   FIRE_NUMBER         320 non-null    object
 2   VERSION_NUMBER      320 non-null    int64
 3   FIRE_YEAR           320 non-null    int64
 4   FIRE_SIZE_HECTARES  320 non-null    float64
 5   SOURCE              320 non-null    object
 6   TRACK_DATE          320 non-null    object
 7   LOAD_DATE           320 non-null    object
 8   FIRE_STATUS         320 non-null    object
 9   FIRE_URL            320 non-null    object
 10  FEATURE_CODE        320 non-null    object
 11  FEATURE_AREA_SQM    320 non-null    float64
 12  FEATURE_LENGTH_M    320 non-null    float64
 13  SHAPE               320 non-null    object
 14  OBJECTID            320 non-null    int64
 15  SE_ANNO_CAD_DATA    0 non-null      float64
dtypes: float64(4), int64(3), object(9)
memory usage: 40.1+ KB

In [8]:
df_hist.describe()

,VERSION_NUMBER,FIRE_YEAR,FIRE_SIZE_HECTARES,OBJECTID,SE_ANNO_CAD_DATA,FEATURE_AREA_SQM,FEATURE_LENGTH_M
count,6.487000e+03,7109.000000,7108.000000,7.109000e+03,0.0,7.109000e+03,7.109000e+03
mean,2.016135e+09,2015.079758,1480.084581,3.178038e+06,NaN,1.479426e+07,1.016253e+04
std,5.395316e+06,6.047060,17562.225545,2.066784e+03,NaN,1.756123e+08,4.381700e+04
min,2.002091e+09,2001.000000,0.000000,3.157167e+06,NaN,4.000000e-03,3.150000e-01
25%,2.011082e+09,2009.000000,2.000000,3.176263e+06,NaN,2.034215e+04,7.695583e+02
50%,2.016102e+09,2015.000000,8.600000,3.178040e+06,NaN,8.607001e+04,1.628781e+03
75%,2.021082e+09,2021.000000,81.600000,3.179817e+06,NaN,8.129474e+05,5.072859e+03
max,2.025051e+09,2024.000000,768915.000000,3.181594e+06,NaN,7.689150e+09,1.382042e+06

In [9]:
df_hist.dtypes

FID                    object
FIRE_NUMBER            object
VERSION_NUMBER        float64
FIRE_YEAR               int64
FIRE_CAUSE             object
FIRE_LABEL             object
FIRE_SIZE_HECTARES    float64
SOURCE                 object
GPS_TRACK_DATE         object
LOAD_DATE              object
FIRE_DATE              object
CREATION_METHOD        object
FEATURE_CODE           object
SHAPE                  object
OBJECTID                int64
SE_ANNO_CAD_DATA      float64
FEATURE_AREA_SQM      float64
FEATURE_LENGTH_M      float64
dtype: object

In [14]:
if not df_hist.empty:
        df_hist.columns = [c.upper() for c in df_hist.columns]
if not df_curr.empty:
        df_curr.columns = [c.upper() for c in df_curr.columns]

In [15]:
all_fires = pd.concat([df_hist, df_curr], ignore_index=True)

In [26]:
all_fires.dtypes

FID                    object
FIRE_NUMBER            object
VERSION_NUMBER        float64
FIRE_YEAR               int64
FIRE_CAUSE             object
FIRE_LABEL             object
FIRE_SIZE_HECTARES    float64
SOURCE                 object
GPS_TRACK_DATE         object
LOAD_DATE              object
FIRE_DATE              object
CREATION_METHOD        object
FEATURE_CODE           object
SHAPE                  object
OBJECTID                int64
SE_ANNO_CAD_DATA      float64
FEATURE_AREA_SQM      float64
FEATURE_LENGTH_M      float64
TRACK_DATE             object
FIRE_STATUS            object
FIRE_URL               object
dtype: object

In [17]:
print(f"Total records fetched  {len(all_fires)}")

Total records fetched  7429

In [18]:
fc_col = next((col for col in ['FIRE_CENTRE', 'MOF_FIRE_CENTRE_NAME'] if col in all_fires.columns), None)

In [19]:
fc_col

In [21]:
if fc_col:
        print(f"Filtering by {fc_col} for 'Cariboo'...")
        cariboo_df = all_fires[all_fires[fc_col].astype(str).str.contains("Cariboo", case=False, na=False)]
else:
        print("Could not identify Fire Centre column. Saving all data.")
        cariboo_df = all_fires

Could not identify Fire Centre column. Saving all data.

In [22]:
wanted_columns = [
        'FIRE_NUMBER', 'FIRE_YEAR', 'FIRE_CAUSE', 'SIZE_HA', 
        'LATITUDE', 'LONGITUDE', 'FIRE_DATE', 'IGNITION_DATE', fc_col
    ]

In [23]:
final_cols = [c for c in wanted_columns if c in cariboo_df.columns]
final_df = cariboo_df[final_cols]

In [24]:
filename = "BC_Cariboo_Wildfires_2001-2024.csv"

In [25]:
final_df.to_csv(filename, index=False)